### ISSUE TITLE
Document shipping just .nim files

### ISSUE THREAD

**Issue by juancarlospaco** [Pebaz/nimporter#40]
I am interested in trying all ways of shipping that nimporter can do, one of the options is not documented along with the others,
thats the option of just shipping the `.nim` files, I made a PIP package that install Nim and other that can install Nimpy,
so would be nice to document on the readme how users can package the `.nim` files.
For new users it might not be so obvious.

You can make your package depend on it `install_requires = ["choosenim_install"]`, heres an example on Windows:

![windows-compile](https://user-images.githubusercontent.com/1189414/107665391-26e8f080-6c6c-11eb-9fa1-742265c1d57b.png)

Commands in order to copy & paste:
- `pip install choosenim_install`
- `pip install nimble_install --install-option="--nimble=nimpy"`

Feel free to use the screenshot if is useful for Docs.
:)

**Comment by Pebaz** [comment]
Hello @juancarlospaco !

I am interested in using `choosenim_install` as a dependency, but I wanted to ask: what does it do if Nim is already installed on the target machine?

Also, I forgot that this was in the readme, but [here](https://github.com/Pebaz/nimporter/#source-distributions) are the instructions for bundling just the Nim files. Using [this](https://github.com/Pebaz/nimporter/#source-distributions) method depends on having the Nim compiler installed on the target machine, which is why I'd like to know what the `choosenim_install` package does if there is already a Nim installation.

Also, Nimporter already automatically installs `nimpy` if the Nim compiler is installed on the target machine.

I am impressed by these packages as I did not think to use PyPi as a method of installing non-python software before ;)

**Comment by juancarlospaco** [comment]
You have admin on the repo of choosenim_install, change what you want, etc.

If it is installed it will install it again, because what if user broke the installation and want to install it again ?.

**Comment by Pebaz** [comment]
Perfect. I think this is good to use then for source distributions. I made a couple changes to allow older Python versions to install `choosenim_install`. Can you reupload to Pypi when you get a chance?

**Comment by juancarlospaco** [comment]
It does whatever choosenim does on a given condition, 
so any improvement should go into choosenim directly instead of workaround specific behaviors.

**Comment by Pebaz** [comment]
I'm sorry I don't understand. Could you explain further?

**Comment by Pebaz** [comment]
Oh you mean Nim's official `choosenim` installer, not `choosenim_install`. Sorry I get it now.

**Comment by Pebaz** [comment]
I updated the readme to include [choosenim_install](https://github.com/Pebaz/nimporter#source-distributions).

I don't want to make it a dependency of Nimporter itself because Nim users with custom installations might not like that.
