### ISSUE TITLE
building wheel with build_nim_extensions()

### ISSUE THREAD

**Issue by willros** [Pebaz/nimporter#68]
Hi,

I am trying to build a binary wheel from the examples in the example folder. The setup.py file looks as follows:

```
from setuptools import setup
import nimporter

setup(
    ...,
    ext_modules=nimporter.build_nim_extensions()
)
```
But when I run `python setup.py bdist_wheel`, I get the following error message:

AttributeError: module 'nimporter' has no attribute 'build_nim_extensions'. Did you mean: 'get_nim_extensions'?

I am on a macOS BigSur, version=11.6.5, and have everything that I need installed.
I have also tried with get_nim_extensions() in the setup.py file, but with no success. 

Thank you very much for this package!

**Comment by Pebaz** [comment]
Is it possible that you happened to be using the [release candidate version of Nimporter 2.0.0](https://github.com/Pebaz/nimporter/releases)? It's a major version increment and has a ton of breaking changes but greatly improves pretty much everything.

I've been looking for people to test out the in-development 2.0.0 version. If you've got some time, you can read the instructions on how to use it here: https://github.com/Pebaz/nimporter/tree/nimporter-v2.0.0rc

It shouldn't be that much different but definitely read through the new README and if there's anything missing let me know.

As for getting you up and running using the 1.x.x Nimporter, you can do: `pip install nimporter==1.1.0`.

Looks like I need to yank that version from Pypi because my automation accidentally uploaded the in-development version up there! 👀

**Comment by Pebaz** [comment]
@willros I yanked the 2.0.0 release candidate from Pypi so it won't affect anyone else for now. If you happen to have time to test out 2.0.0 let me know! 😁

**Comment by willros** [comment]
Thank you @Pebaz for a quick and informative answer! 

Yes, I was using the 2.0.0 version of Nimporter. 

I will for sure test the new version! Where do you want me to share my thoughts of it? 

Thanks,
William

**Comment by willros** [comment]
This is what I have so far:

After trying different structures which did not generate modules working when importing them to python, I tried this structure: 

```
.
├── nimlibtest
│   ├── __init__.py
│   ├── nimlibtest.nim
│   ├── nimlibtest.nim.cfg
│   ├── nimlibtest.nimble
│   └── nimlibtest.py
└── setup.py
````
with `setup.py`:

```
import setuptools
from nimporter import get_nim_extensions, WINDOWS, MACOS, LINUX

setuptools.setup(
    name='nimlibtest',
    install_requires=['nimporter'],
    py_modules = ['nimlibtest'],
    ext_modules=get_nim_extensions(platforms=[WINDOWS, LINUX, MACOS])
)
``` 
then:

```
python setup.py sdist
cd dist/
pip install <package.tar>
```

Doing all above works for me. I had to try different folder structures and include different files.

*Also some potential fixes I have noticed:*

In the setup.py example, there is one comma missing:

```
setuptools.setup(
    name='calculatorlib',
    install_requires=['nimporter'], # missing comma in the example code block! 
    py_modules=['calculatorlib.py'],
    ext_modules=get_nim_extensions(platforms=[WINDOWS, LINUX, MACOS])
)
````
* Figures at the top → the rightmost file says “calculatorlib.nim”. Should that instead have a .py extension?

**Comment by willros** [comment]
Another question I have about the v.2:¨

In v1. it is possible to add `ext_modules=nimporter.build_nim_extensions(danger=True)` to the `setup.py` file. This options seems to not be available with the `nimporter.get_nim_extensions` function. I tried to add `nim c -d:danger myproject.nim` flag in the `.nim.cfg.` file, but doing so, `python setup.py sdist` fails.

How can I realease the switch in v.2 of nimporter?

Thanks again!

**Comment by Pebaz** [comment]
Hi @willros ! Sorry for the late response, i haven't had a chance to look into this yet. As for the flags, v2 only allows flags inside the *.nim.cfg file for Extension Libraries. Extension Modules we're redesigned to be easily importable for Python folks and Extension Libraries are supposed to be configurable and are allowed to have dependencies.

I'll try to look deeper into this today. Try to check out the new readme on the v2 branch, there are some important details regarding breaking changes (like danger=true).

Thanks for checking the new branch out!

**Comment by Pebaz** [comment]
@willros I was able to find a reference to the required (as of v2) folder structure for Extension Libraries [here](https://github.com/Pebaz/nimporter/tree/e1aaddf263d992fc534b620103b00a807b574fd8#-extension-modules--extension-libraries) (also `nimporter init lib` can be used or the [Cookiecutter template](https://github.com/Pebaz/template-nimporter-ext-lib) can be used directly). Basically, in order to be able to setup custom CLI flags, have dependencies, and import other Nim source files, Extension Libraries must adhere to this new v2 folder structure. It got to the point in v1 that it was just plain difficult to determine what was what, so accepting some limitations actually ended up solidifying the underlying idea.

I think you should be up and running now but if you have any questions or other issues, let me know and I'll help out in any way I can. I've tried to answer quicker but it's been crazy on my end lol 💢

I'll go ahead and close this for now but feel free to reopen it should you run into any more issues. 🙂
